# Site settings
title: Maffblaster's personal blog
email: Maffblaster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        A blog about many things, but particularly: practicality, efficiency, critical thinking, implementing technology for freedom, the future, and the Christian faith. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maffblaster.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  maffblaster

# Define where things are
# This can be '' to hide the Github nav button
github: 'scotte/jekyll-clean'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis


disqus: ''
comments: true

source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
data_source: ./_data
timezone: America/Los_Angeles

# Testing

highlighter: pygments
markdown: redcarpet

# Outputting
permalink:     date

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']