# Site settings
title: Maffblaster's personal blog
email: Maffblaster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        A blog about many things, but particularly the Christian faith.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maffblaster.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  maffblaster

# Build settings
markdown: kramdown
