# Site settings
title: Maffblaster's webspace
email: Maffblaster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        A blog about many things, but particularly: practicality, efficiency, critical thinking, implementing technology for freedom, the future, and the Christian faith. 
baseurl: "" # the subpath of the site, e.g. /blog/
url: "http://maffblaster.github.io" # the base hostname and protocol for the site
twitter_username:
github_username:  maffblaster
source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
data_source: ./_data
timezone: America/Los_Angeles
encoding: "utf-8"

# Build settings
markdown: kramdown

# Output
permalink:     date